--------------------------------------------------------
--  File created - Sunday-April-27-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYEE_TABLE" 
   (	"EMPLOYEE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLOYEE_NAME" VARCHAR2(20 BYTE), 
	"EMPLOYEE_ADDRESS" VARCHAR2(20 BYTE), 
	"EMPLOYEE_TEL" NUMBER, 
	"EMPLOYEE_PASSWORD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.EMPLOYEE_TABLE
SET DEFINE OFF;
Insert into SYSTEM.EMPLOYEE_TABLE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_ADDRESS,EMPLOYEE_TEL,EMPLOYEE_PASSWORD) values (101,'Harindu','Gampaha',765506968,'123');
Insert into SYSTEM.EMPLOYEE_TABLE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_ADDRESS,EMPLOYEE_TEL,EMPLOYEE_PASSWORD) values (102,'Kamal','Nugegoda',72684090,null);
--------------------------------------------------------
--  DDL for Index EMPLOYEE_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYEE_TABLE_PK" ON "SYSTEM"."EMPLOYEE_TABLE" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE_TABLE" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE_TABLE" ADD CONSTRAINT "EMPLOYEE_TABLE_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
