--------------------------------------------------------
--  File created - Wednesday-April-16-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDER_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORDER_TABLE" 
   (	"ORDER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ORDER_TOTAL_PRICE" NUMBER, 
	"ORDER_CUSTOMER_ID" NUMBER, 
	"ORDER_STATUS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ORDER_TABLE
SET DEFINE OFF;
Insert into SYSTEM.ORDER_TABLE (ORDER_ID,ORDER_TOTAL_PRICE,ORDER_CUSTOMER_ID,ORDER_STATUS) values (1,20000,1,'1');
