--------------------------------------------------------
--  File created - Thursday-April-17-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDER_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORDER_TABLE" 
   (	"ORDER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ORDER_TOTAL_PRICE" NUMBER, 
	"ORDER_CUSTOMER_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ORDER_TABLE
SET DEFINE OFF;
Insert into SYSTEM.ORDER_TABLE (ORDER_ID,ORDER_TOTAL_PRICE,ORDER_CUSTOMER_ID) values (1,492,23);
Insert into SYSTEM.ORDER_TABLE (ORDER_ID,ORDER_TOTAL_PRICE,ORDER_CUSTOMER_ID) values (2,431046,23);
Insert into SYSTEM.ORDER_TABLE (ORDER_ID,ORDER_TOTAL_PRICE,ORDER_CUSTOMER_ID) values (3,505416,23);
Insert into SYSTEM.ORDER_TABLE (ORDER_ID,ORDER_TOTAL_PRICE,ORDER_CUSTOMER_ID) values (4,639615,23);
Insert into SYSTEM.ORDER_TABLE (ORDER_ID,ORDER_TOTAL_PRICE,ORDER_CUSTOMER_ID) values (5,639615,23);
--------------------------------------------------------
--  DDL for Index ORDER_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ORDER_TABLE_PK" ON "SYSTEM"."ORDER_TABLE" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDER_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORDER_TABLE" MODIFY ("ORDER_ID" NOT NULL ENABLE);
