--------------------------------------------------------
--  File created - Saturday-March-29-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REVIEW_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REVIEW_TABLE" 
   (	"REVIEW_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REVIEW_CUSTOMER_ID" NUMBER, 
	"REVIEW_FOOD_ID" NUMBER, 
	"REVIEW_CONTENT" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.REVIEW_TABLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index REVIEW_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."REVIEW_TABLE_PK" ON "SYSTEM"."REVIEW_TABLE" ("REVIEW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REVIEW_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REVIEW_TABLE" MODIFY ("REVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."REVIEW_TABLE" ADD CONSTRAINT "REVIEW_TABLE_PK" PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REVIEW_TABLE" ADD CONSTRAINT "REVIEW_TABLE_FK1" FOREIGN KEY ("REVIEW_CUSTOMER_ID")
	  REFERENCES "SYSTEM"."CUSTOMER_TABLE" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."REVIEW_TABLE" ADD CONSTRAINT "REVIEW_TABLE_FK2" FOREIGN KEY ("REVIEW_FOOD_ID")
	  REFERENCES "SYSTEM"."FOOD_TABLE" ("FOOD_ID") ENABLE;
