--------------------------------------------------------
--  File created - Monday-March-31-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBORDER_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SUBORDER_TABLE" 
   (	"SUBORDER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SUBORDER_CUSTOMER_ID" NUMBER, 
	"SUBORDER_FOOD_ID" NUMBER, 
	"SUBORDER_QTY" VARCHAR2(20 BYTE), 
	"SUBORDER_ORDER_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SUBORDER_TABLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SUBORDER_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SUBORDER_TABLE_PK" ON "SYSTEM"."SUBORDER_TABLE" ("SUBORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUBORDER_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBORDER_TABLE" MODIFY ("SUBORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBORDER_TABLE" ADD CONSTRAINT "SUBORDER_TABLE_PK" PRIMARY KEY ("SUBORDER_ID")
  USING INDEX "SYSTEM"."SUBORDER_TABLE_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBORDER_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBORDER_TABLE" ADD CONSTRAINT "SUBORDER_TABLE_FK2" FOREIGN KEY ("SUBORDER_FOOD_ID")
	  REFERENCES "SYSTEM"."FOOD_TABLE" ("FOOD_ID") ENABLE;
