--------------------------------------------------------
--  File created - Sunday-April-27-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBORDER_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SUBORDER_TABLE" 
   (	"SUBORDER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SUBORDER_FOOD_ID" NUMBER, 
	"SUBORDER_QTY" NUMBER, 
	"SUBORDER_ORDER_ID" NUMBER, 
	"SUBORDER_SUPPLIER_ID" NUMBER, 
	"SUBORDER_STATUS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SUBORDER_TABLE
SET DEFINE OFF;
Insert into SYSTEM.SUBORDER_TABLE (SUBORDER_ID,SUBORDER_FOOD_ID,SUBORDER_QTY,SUBORDER_ORDER_ID,SUBORDER_SUPPLIER_ID,SUBORDER_STATUS) values (1,36,3,7,21,'Completed');
Insert into SYSTEM.SUBORDER_TABLE (SUBORDER_ID,SUBORDER_FOOD_ID,SUBORDER_QTY,SUBORDER_ORDER_ID,SUBORDER_SUPPLIER_ID,SUBORDER_STATUS) values (2,37,2,8,21,'Completed');
Insert into SYSTEM.SUBORDER_TABLE (SUBORDER_ID,SUBORDER_FOOD_ID,SUBORDER_QTY,SUBORDER_ORDER_ID,SUBORDER_SUPPLIER_ID,SUBORDER_STATUS) values (3,48,5,9,25,'Pending');
Insert into SYSTEM.SUBORDER_TABLE (SUBORDER_ID,SUBORDER_FOOD_ID,SUBORDER_QTY,SUBORDER_ORDER_ID,SUBORDER_SUPPLIER_ID,SUBORDER_STATUS) values (4,44,3,10,22,'Pending');
Insert into SYSTEM.SUBORDER_TABLE (SUBORDER_ID,SUBORDER_FOOD_ID,SUBORDER_QTY,SUBORDER_ORDER_ID,SUBORDER_SUPPLIER_ID,SUBORDER_STATUS) values (5,47,1,10,25,'Pending');
Insert into SYSTEM.SUBORDER_TABLE (SUBORDER_ID,SUBORDER_FOOD_ID,SUBORDER_QTY,SUBORDER_ORDER_ID,SUBORDER_SUPPLIER_ID,SUBORDER_STATUS) values (6,45,2,10,22,'Pending');
Insert into SYSTEM.SUBORDER_TABLE (SUBORDER_ID,SUBORDER_FOOD_ID,SUBORDER_QTY,SUBORDER_ORDER_ID,SUBORDER_SUPPLIER_ID,SUBORDER_STATUS) values (7,51,3,11,26,'Pending');
Insert into SYSTEM.SUBORDER_TABLE (SUBORDER_ID,SUBORDER_FOOD_ID,SUBORDER_QTY,SUBORDER_ORDER_ID,SUBORDER_SUPPLIER_ID,SUBORDER_STATUS) values (8,52,2,12,26,'Pending');
Insert into SYSTEM.SUBORDER_TABLE (SUBORDER_ID,SUBORDER_FOOD_ID,SUBORDER_QTY,SUBORDER_ORDER_ID,SUBORDER_SUPPLIER_ID,SUBORDER_STATUS) values (9,53,2,13,27,'Completed');
--------------------------------------------------------
--  DDL for Index SUBORDER_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SUBORDER_TABLE_PK" ON "SYSTEM"."SUBORDER_TABLE" ("SUBORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUBORDER_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBORDER_TABLE" MODIFY ("SUBORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUBORDER_TABLE" ADD CONSTRAINT "SUBORDER_TABLE_PK" PRIMARY KEY ("SUBORDER_ID")
  USING INDEX "SYSTEM"."SUBORDER_TABLE_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBORDER_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUBORDER_TABLE" ADD CONSTRAINT "SUBORDER_TABLE_FK1" FOREIGN KEY ("SUBORDER_SUPPLIER_ID")
	  REFERENCES "SYSTEM"."SUPPLIER_TABLE" ("SUPPLIER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."SUBORDER_TABLE" ADD CONSTRAINT "SUBORDER_TABLE_FK2" FOREIGN KEY ("SUBORDER_FOOD_ID")
	  REFERENCES "SYSTEM"."FOOD_TABLE" ("FOOD_ID") ENABLE;
  ALTER TABLE "SYSTEM"."SUBORDER_TABLE" ADD CONSTRAINT "SUBORDER_TABLE_FK4" FOREIGN KEY ("SUBORDER_ORDER_ID")
	  REFERENCES "SYSTEM"."ORDER_TABLE" ("ORDER_ID") ENABLE;
