--------------------------------------------------------
--  File created - Tuesday-April-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUPPLIER_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SUPPLIER_TABLE" 
   (	"SUPPLIER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SUPPLIER_NAME" VARCHAR2(20 BYTE), 
	"SUPPLIER_ADDRESS" VARCHAR2(20 BYTE), 
	"SUPPLIER_TEL" NUMBER, 
	"SUPPLIER_COMPANY" VARCHAR2(20 BYTE), 
	"SUPPLIER_PASSWORD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SUPPLIER_TABLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SUPPLIER_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SUPPLIER_TABLE_PK" ON "SYSTEM"."SUPPLIER_TABLE" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUPPLIER_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SUPPLIER_TABLE" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SUPPLIER_TABLE" ADD CONSTRAINT "SUPPLIER_TABLE_PK" PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
