--------------------------------------------------------
--  File created - Saturday-March-29-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOOD_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FOOD_TABLE" 
   (	"FOOD_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FOOD_NAME" VARCHAR2(20 BYTE), 
	"FOOD_DESCRIPTION" VARCHAR2(20 BYTE), 
	"FOOD_PIC" BLOB, 
	"FOOD_PRICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FOOD_PIC") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SYSTEM.FOOD_TABLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FOOD_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FOOD_TABLE_PK" ON "SYSTEM"."FOOD_TABLE" ("FOOD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FOOD_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FOOD_TABLE" MODIFY ("FOOD_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FOOD_TABLE" ADD CONSTRAINT "FOOD_TABLE_PK" PRIMARY KEY ("FOOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
